CREATE TABLE `Trail-Cache-Log` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` VARCHAR(64) NOT NULL,
  `city` VARCHAR(100) DEFAULT NULL,
  `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `unique_combo` (`state`, `city`)
);
